/**
 * The five templates that predate the verification suite.
 *
 * These payloads are hand-authored strings users have already shared, pinned
 * byte-for-byte by template-url.spec.ts against TEMPLATE_BASELINES. They are not
 * regenerated from anything and must not be edited.
 */
export const BUILT_IN_TEMPLATE_IDS = [
  '4-Bar',
  'Watt_I',
  'Watt_II',
  'Stephenson_III',
  'Slider_Crank',
] as const;

export type BuiltInTemplateID = (typeof BUILT_IN_TEMPLATE_IDS)[number];

/**
 * The wider linkage library, every entry of which is a mechanism the
 * verification suite already asserts on.
 *
 * Their payloads are *generated* from those fixtures rather than typed in — see
 * the generated block in TEMPLATE_LINKAGES below — so a template cannot quietly
 * become a different linkage than the one the tests cover.
 */
export const LIBRARY_TEMPLATE_IDS = [
  'Whitworth_Quick_Return',
  'Scotch_Yoke',
  'Cylinder_Boom',
  'Pivoting_Gripper',
  'Radial_Engine',
  'Chebyshev_Straight_Line',
  'Windshield_Wiper',
  'Elliptical_Crank',
  'Jansen_Leg',
] as const;

export type LibraryTemplateID = (typeof LIBRARY_TEMPLATE_IDS)[number];

export type TemplateID = BuiltInTemplateID | LibraryTemplateID;

/** Every template the library dialog offers, in the order it offers them. */
export const TEMPLATE_IDS: readonly TemplateID[] = [
  ...BUILT_IN_TEMPLATE_IDS,
  ...LIBRARY_TEMPLATE_IDS,
];

/**
 * Production URL payloads used by the template dialog and regression tests.
 *
 * The library entries between the generated markers are written by
 * `npm run template-payloads`, which encodes the matching FIXTURE_GALLERY entry.
 * template-payloads.spec.ts fails if a stored payload stops matching what its
 * fixture encodes to, the same way docs/fixture-urls.md is kept honest.
 *
 * The generator lives in a spec rather than a plain node script because
 * encoding needs the app's own model and codec, and because nothing test-only
 * may be imported from here: this file ships, and importing src/test-utils
 * would drag every fixture into the bundle.
 */
export const TEMPLATE_LINKAGES: Record<TemplateID, string> = {
  '4-Bar':
    '0P.TY.K,0.101.MA,A,0mv,0VU,0.GB,B,0e_,E6,0.GC,C,l1,WW,0.KD,D,qD,0Pk,0..YRAB,AB,Fe,Fe,0ix,08i,c5cae9,A,B,,.YRBC,BC,Fe,Fe,32,NJ,303e9f,B,C,,.YRCD,CD,Fe,Fe,nd,3P,0d125a,C,D,,...JBq',
  Watt_I:
    '0P.TY.K,0.101.MA,A,0Qh,0Kn,0.GB,B,0e1,9i,0.GC,C,bT,LF,0.GD,D,0G5,tZ,0.GE,E,V5,1_z,0.GF,F,1mM,1Gv,0.KG,G,1rt,0ey,0..YRAB,AB,Fe,Fe,0XM,05Z,c5cae9,A,B,,.YRBCD,BCD,Fe,Fe,06D,Sr,303e9f,B,C,D,,.YRDE,DE,Fe,Fe,7W,1RG,0d125a,D,E,,.YREF,EF,Fe,Fe,17j,1dx,B2DFDB,E,F,,.YRFCG,FCG,Fe,Fe,1PE,KQ,26A69A,F,C,G,,...JAp',
  Watt_II:
    '0P.TY.K,0.101.MA,A,0Vf,0Vd,0.GB,B,0mZ,08A,0.GC,C,06Y,LC,0.GD,D,1MR,J2,0.KE,E,rw,0j2,0.GF,F,2ic,ID,0.KG,G,2lk,0Zt,0..YRAB,AB,Fe,Fe,0e6,0Ju,c5cae9,A,B,,.YRBC,BC,Fe,Fe,0RY,6X,303e9f,B,C,,.YRCDE,CDE,Fe,Fe,ic,01d,0d125a,C,D,E,,.YRDF,DF,Fe,Fe,21X,Id,B2DFDB,D,F,,.YRFG,FG,Fe,Fe,2kA,08r,26A69A,F,G,,...JBm',
  Stephenson_III:
    '0P.TY.K,0.101.MA,A,0YP,0ce,0.GB,B,0cQ,0FI,0.GC,C,lC,1-,0.KD,D,ow,0U1,0.GE,E,033,D-,0.GF,F,Dc,nj,0.KG,G,1M0,GJ,0..YRAB,AB,Fe,Fe,0aP,0Qz,c5cae9,A,B,,.YRBCE,BCE,Fe,Fe,1w,E,303e9f,B,C,E,,.YRCD,CD,Fe,Fe,n3,0E1,0d125a,C,D,,.YREF,EF,Fe,Fe,5H,Vs,B2DFDB,E,F,,.YRFG,FG,Fe,Fe,np,X0,26A69A,F,G,,...JBe',
  Slider_Crank:
    '0P.TY.K,0.101.MA,A,0mA,0c,0.GB,B,0Yt,bK,0.GC,C,il,H-,0.LD,D,il,H-,0..YRAB,AB,Fe,Fe,0fW,IN,c5cae9,A,B,,.YRBC,BC,Fe,Fe,4y,Rf,303e9f,B,C,,.YPCD,CD,Fe,0,0,0,,C,D,,...JAe',
  // <generated by `npm run template-payloads` — do not edit by hand>
  Whitworth_Quick_Return:
    '2P.Fe,1E8.K,0.1011.MA,A,0,0,0.GB,B,0,ku,0.KC,C,Fe,0,0.GD,D,095,1A7,0.HP,P,0,ku,0,CD,C,D..YRAB,AB,Fe,Fe,0,NS,c5cae9,A,B,,.YRCD,CD,Fe,Fe,3H,b4,303e9f,C,D,,.YPBP,BP,Fe,0,0,0,,B,P,,...N_w',
  Scotch_Yoke:
    '2P.Fe,1E8.K,0.1011.MA,A,0,0,0.GB,B,Fe,0,0.OC,C,Fe,0VG,0.GD,D,Fe,Fe,0.HE,E,Fe,0,0,CD,C,D.LF,F,Fe,0VG,0..YRAB,AB,Fe,Fe,7q,0,c5cae9,A,B,,.YRCD,CD,Fe,Fe,Fe,07q,303e9f,C,D,,.YPBE,BE,Fe,0,0,0,,B,E,,.YPCF,CF,Fe,0,0,0,,C,F,,...N_Z',
  Cylinder_Boom:
    '2P.Fe,1E8.K,0.1011.KO,O,0,0,0.GC,C,0,_W,0.KG,G,ku,0,0.GN,N,Fe,fh,0.OP,P,VG,Kr,0.pS,S,VG,Kr,0,GN,G,N..YROC,OC,Fe,Fe,0,VG,c5cae9,O,C,,.YRGN,GN,Fe,Fe,VG,Kr,303e9f,G,N,,.YRPC,PC,Fe,Fe,Fe,fh,0d125a,P,C,,.YPPS,PS,Fe,0,0,0,,P,S,,...N_f',
  Pivoting_Gripper:
    '2P.Fe,1E8.K,0.1011.GA,A,0U5,0,0.GM,M,DZ,0,0.GB,B,0Hj,Fj,0.GC,C,0Hj,0FZ,0.KF,F,0V6,X9,0.GG,G,A,X9,0.GK,K,_o,GS,0.KH,H,0V6,0X0,0.GI,I,A,0X0,0.GJ,J,_d,0Bn,0.NP,P,0U5,0,0.LN,N,DZ,0,0..YRAMBC,AMBC,Fe,Fe,0C-,2,c5cae9,A,M,B,C,,.YRBG,BG,Fe,Fe,08o,OR,303e9f,B,G,,.YRCI,CI,Fe,Fe,08o,0OH,0d125a,C,I,,.YRFGK,FGK,Fe,Fe,Ae,Rb,B2DFDB,F,G,K,,.YRHIJ,HIJ,Fe,Fe,Aa,0Px,26A69A,H,I,J,,.YPAP,AP,Fe,0,0,0,,A,P,,.YPMN,MN,Fe,0,0,0,,M,N,,...N_j',
  Radial_Engine:
    '2P.Fe,1E8.K,0.1011.MO,O,0,0,0.GA,A,Fe,0,0.GB,B,0,iC,0.GC,C,0SK,0GM,0.GD,D,pm,0Tu,0.LP,P,0,iC,OZ.LQ,Q,0SK,0GM,vH.LR,R,pm,0Tu,1Q0..YROA,OA,Fe,Fe,7q,0,c5cae9,O,A,,.YRAB,AB,Fe,Fe,7q,M6,303e9f,A,B,,.YRAC,AC,Fe,Fe,06M,08B,0d125a,A,C,,.YRAD,AD,Fe,Fe,Xi,0Ey,B2DFDB,A,D,,.YPBP,BP,Fe,0,0,0,,B,P,,.YPCQ,CQ,Fe,0,0,0,,C,Q,,.YPDR,DR,Fe,0,0,0,,D,R,,...N_T',
  Chebyshev_Straight_Line:
    '2P.Fe,1E8.K,0.1011.MG,G,0VG,0,0.GA,A,0Fe,_W,0.GB,B,Fe,_W,0.GM,M,0,_W,0.KH,H,VG,0,0..YRGB,GB,Fe,Fe,07q,VG,c5cae9,G,B,,.YRABM,ABM,Fe,Fe,0,_W,303e9f,A,B,M,,.YRAH,AH,Fe,Fe,7q,VG,0d125a,A,H,,...N_5',
  Windshield_Wiper:
    '2P.Fe,1E8.K,0.1011.MO,O,0,0,0.GA,A,Im,0,0.GB,B,1H-,YA,0.GT,T,1K6,qo,0.KH,H,1E8,0,0..YROA,OA,Fe,Fe,9O,0,c5cae9,O,A,,.YRAB,AB,Fe,Fe,oO,H5,303e9f,A,B,,.YRBHT,BHT,Fe,Fe,1HQ,S-,0d125a,B,H,T,,...N_5',
  Elliptical_Crank:
    '2P.Fe,1E8.K,0.1011.MA,A,0ix,X,0.GB,B,0zu,7O,0.GC,C,0qC,Lr,0.GD,D,085,Av,0.GE,E,aY,v,0.KF,F,0,0,0.LP,P,aY,v,03..YRAB,AB,Fe,Fe,0rQ,3y,c5cae9,A,B,,.YRBC,BC,Fe,Fe,0v2,Ed,303e9f,B,C,,.YRCDE,CDE,Fe,Fe,07x,BD,0d125a,C,D,E,,.YRDF,DF,Fe,Fe,043,5S,B2DFDB,D,F,,.YPEP,EP,Fe,0,0,0,,E,P,,...N_V',
  Jansen_Leg:
    '2P.3Qm,1E8.K,0.1011.MO,O,0,0,0.GA,A,3gO,0,0.KG,G,09Hm,01vu,0.GB,B,05tE,7ee,0.GC,C,0IGg,1-F,0.GD,D,06b8,0B7B,0.GE,E,0ETW,06sL,0.GF,F,0AYO,0MPj,0..YROA,OA,Fe,Fe,1rC,0,c5cae9,O,A,,.YRAB,AB,Fe,Fe,016R,3qK,303e9f,A,B,,.YRGBC,GBC,Fe,Fe,0B8Z,2ag,0d125a,G,B,C,,.YRAD,AD,Fe,Fe,01TO,05Zc,B2DFDB,A,D,,.YRGD,GD,Fe,Fe,07xS,06WY,26A69A,G,D,,.YRCE,CE,Fe,Fe,0GN5,02RZ,00695C,C,E,,.YRDEF,DEF,Fe,Fe,0AXh,0DT4,c5cae9,D,E,F,,...N_c',
  // </generated>
};
