/**
 * The five templates that predate the verification suite.
 *
 * These payloads are hand-authored strings users have already shared, pinned
 * byte-for-byte by template-url.spec.ts against TEMPLATE_BASELINES. They are not
 * regenerated from anything and must not be edited.
 */
export const BUILT_IN_TEMPLATE_IDS = [
  '4-Bar',
  'Watt_I',
  'Watt_II',
  'Stephenson_III',
  'Slider_Crank',
] as const;

export type BuiltInTemplateID = (typeof BUILT_IN_TEMPLATE_IDS)[number];

/**
 * The wider linkage library, every entry of which is a mechanism the
 * verification suite already asserts on.
 *
 * Their payloads are *generated* from those fixtures rather than typed in — see
 * the generated block in TEMPLATE_LINKAGES below — so a template cannot quietly
 * become a different linkage than the one the tests cover.
 */
export const LIBRARY_TEMPLATE_IDS = [
  'Whitworth_Quick_Return',
  'Scotch_Yoke',
  'Cylinder_Boom',
  'Cylinder_Gripper',
  'Radial_Engine',
  'Chebyshev_Straight_Line',
  'Windshield_Wiper',
  'Elliptical_Crank',
  'Jansen_Leg',
  'Backhoe_Bucket',
  'Toggle_Press',
  'Scissor_Lift',
  'Shaper_Quick_Return',
  'Pedaling_Leg',
  'Oscillating_Fan',
  'Pumpjack',
  'Punch_Press',
  'Derrick_Crane',
  'Toggle_Clamp',
  'Offset_Load_Rocker',
] as const;

export type LibraryTemplateID = (typeof LIBRARY_TEMPLATE_IDS)[number];

export type TemplateID = BuiltInTemplateID | LibraryTemplateID;

/** Every template the library dialog offers, in the order it offers them. */
export const TEMPLATE_IDS: readonly TemplateID[] = [
  ...BUILT_IN_TEMPLATE_IDS,
  ...LIBRARY_TEMPLATE_IDS,
];

/**
 * Production URL payloads used by the template dialog and regression tests.
 *
 * The library entries between the generated markers are written by
 * `npm run template-payloads`, which encodes the matching FIXTURE_GALLERY entry.
 * template-payloads.spec.ts fails if a stored payload stops matching what its
 * fixture encodes to, the same way docs/fixture-urls.md is kept honest.
 *
 * The generator lives in a spec rather than a plain node script because
 * encoding needs the app's own model and codec, and because nothing test-only
 * may be imported from here: this file ships, and importing src/test-utils
 * would drag every fixture into the bundle.
 */
export const TEMPLATE_LINKAGES: Record<TemplateID, string> = {
  '4-Bar':
    '2P.Ay,1E8.K,0.1011.6A,A,0mv,0VU,0.0B,B,0e_,E6,0.0C,C,l1,WW,0.4D,D,qD,0Pk,0..YRAB,AB,Fe,Fe,0ix,08i,c5cae9,A,B,,.YRBC,BC,Fe,Fe,32,NJ,303e9f,B,C,,.YRCD,CD,Fe,Fe,nd,3P,0d125a,C,D,,...N_v',
  Watt_I:
    '2P.Ay,1E8.K,0.1011.6A,A,0Qh,0Kn,0.0B,B,0e1,9i,0.0C,C,bT,LF,0.0D,D,0G5,tZ,0.0E,E,V5,1_z,0.0F,F,1mM,1Gv,0.4G,G,1rt,0ey,0..YRAB,AB,Fe,Fe,0XM,05Z,c5cae9,A,B,,.YRBCD,BCD,Fe,Fe,06D,Sr,303e9f,B,C,D,,.YRDE,DE,Fe,Fe,7W,1RG,0d125a,D,E,,.YREF,EF,Fe,Fe,17j,1dx,B2DFDB,E,F,,.YRFCG,FCG,Fe,Fe,1PE,KQ,26A69A,F,C,G,,...N_u',
  Watt_II:
    '2P.Ay,1E8.K,0.1011.6A,A,0Vf,0Vd,0.0B,B,0mZ,08A,0.0C,C,06Y,LC,0.0D,D,1MR,J2,0.4E,E,rw,0j2,0.0F,F,2ic,ID,0.4G,G,2lk,0Zt,0..YRAB,AB,Fe,Fe,0e6,0Ju,c5cae9,A,B,,.YRBC,BC,Fe,Fe,0RY,6X,303e9f,B,C,,.YRCDE,CDE,Fe,Fe,ic,01d,0d125a,C,D,E,,.YRDF,DF,Fe,Fe,21X,Id,B2DFDB,D,F,,.YRFG,FG,Fe,Fe,2kA,08r,26A69A,F,G,,...N_r',
  Stephenson_III:
    '2P.Ay,1E8.K,0.1011.6A,A,0YP,0ce,0.0B,B,0cQ,0FI,0.0C,C,lC,1-,0.4D,D,ow,0U1,0.0E,E,033,D-,0.0F,F,Dc,nj,0.4G,G,1M0,GJ,0..YRAB,AB,Fe,Fe,0aP,0Qz,c5cae9,A,B,,.YRBCE,BCE,Fe,Fe,1w,E,303e9f,B,C,E,,.YRCD,CD,Fe,Fe,n3,0E1,0d125a,C,D,,.YREF,EF,Fe,Fe,5H,Vs,B2DFDB,E,F,,.YRFG,FG,Fe,Fe,np,X0,26A69A,F,G,,...N_j',
  Slider_Crank:
    '2P.Ay,1E8.K,0.1011.6A,A,0mA,0c,0.0B,B,0Yt,bK,0.0C,C,il,H-,0.5D,D,il,H-,0..YRAB,AB,Fe,Fe,0fW,IN,c5cae9,A,B,,.YRBC,BC,Fe,Fe,4y,Rf,303e9f,B,C,,.YPCD,CD,Fe,0,0,0,,C,D,,...N_j',
  // <generated by `npm run template-payloads` — do not edit by hand>
  Whitworth_Quick_Return:
    '2P.Ay,1E8.K,0.1011.6A,A,0,0,0.0B,B,0,ku,0.4C,C,Fe,0,0.0D,D,095,1A7,0.1P,P,0,ku,0,CD,C,D..YRAB,AB,Fe,Fe,0,NS,c5cae9,A,B,,.YRCD,CD,Fe,Fe,3H,b4,303e9f,C,D,,.YPBP,BP,Fe,0,0,0,,B,P,,...N_w',
  Scotch_Yoke:
    '2P.Ay,1E8.K,0.1011.6A,A,0,0,0.0B,B,Fe,0,0.8C,C,Fe,0VG,0.0D,D,Fe,S8,0.1E,E,Fe,0,0,CD,C,D.5F,F,Fe,0VG,0..YRAB,AB,Fe,Fe,7q,0,c5cae9,A,B,,.YRCD,CD,Fe,Fe,Fe,01a,303e9f,C,D,,.YPBE,BE,Fe,0,0,0,,B,E,,.YPCF,CF,Fe,0,0,0,,C,F,,...N_Z',
  Cylinder_Boom:
    '2P.Ay,Fe.K,0.1011.4O,O,0,0,0.0C,C,0,_W,0.4G,G,ku,0,0.0N,N,Ju,Z-,0.8P,P,R0,QX,0.ZS,S,R0,QX,0,GN,G,N..YROC,OC,Fe,Fe,0,VG,c5cae9,O,C,,.YRGN,GN,Fe,Fe,XO,I0,303e9f,G,N,,.YRPC,PC,Fe,Fe,DW,iW,0d125a,P,C,,.YPPS,PS,Fe,0,0,0,,P,S,,...N_e',
  Cylinder_Gripper:
    '2P.Ay,1E8.K,0.1011.4A,A,02SG,ku,0.0B,B,0185,uK,0.8C,C,019F,uC,0.0D,D,Ay,11e,0.4G,G,_W,ku,0.0H,H,1HG,S8,0.0I,I,2hu,VG,0.4J,J,_W,0ku,0.0K,K,hm,0S8,0.0L,L,2hu,0VG,0.ZE,E,019F,uC,0,AB,A,B..YRAB,AB,Fe,Fe,01oB,pc,c5cae9,A,B,,.YRCD,CD,Fe,Fe,0V9,yw,303e9f,C,D,,.YRDGHI,DGHI,Fe,Fe,1Hf,g_,0d125a,D,G,H,I,,.YRHK,HK,Fe,Fe,_W,0,B2DFDB,H,K,,.YRJKL,JKL,Fe,Fe,1Sj,0ZR,26A69A,J,K,L,,.YPCE,CE,Fe,0,0,0,,C,E,,...N_N',
  Radial_Engine:
    '2P.Ay,1E8.K,0.1011.6O,O,0,0,0.0A,A,Fe,0,0.0B,B,0,iC,0.0C,C,0UD,9q,0.0D,D,0L9,0T6,0.0E,E,Vy,0hz,0.0F,F,wV,J0,0.5P,P,0,iC,OZ.5Q,Q,0UD,9q,iB.5R,R,0L9,0T6,-q.5S,S,Vy,0hz,1JT.5T,T,wV,J0,1d5..YROA,OA,Fe,Fe,7q,0,c5cae9,O,A,,.YRAB,AB,Fe,Fe,7q,M6,303e9f,A,B,,.YRAC,AC,Fe,Fe,07J,4w,0d125a,A,C,,.YRAD,AD,Fe,Fe,02m,0EZ,B2DFDB,A,D,,.YRAE,AE,Fe,Fe,No,0L_,26A69A,A,E,,.YRAF,AF,Fe,Fe,b3,9W,00695C,A,F,,.YPBP,BP,Fe,0,0,0,,B,P,,.YPCQ,CQ,Fe,0,0,0,,C,Q,,.YPDR,DR,Fe,0,0,0,,D,R,,.YPES,ES,Fe,0,0,0,,E,S,,.YPFT,FT,Fe,0,0,0,,F,T,,...N_F',
  Chebyshev_Straight_Line:
    '2P.Ay,1E8.2,0.1011.6G,G,0VG,0,0.0A,A,0Fe,_W,0.0B,B,Fe,_W,0.GM,M,0,_W,0.4H,H,VG,0,0..YRGB,GB,Fe,Fe,07q,VG,c5cae9,G,B,,.YRABM,ABM,Fe,Fe,0,_W,303e9f,A,B,M,,.YRAH,AH,Fe,Fe,7q,VG,0d125a,A,H,,...N_5',
  Windshield_Wiper:
    '2P.Ay,1E8.K,0.1011.6O,O,0si,0iC,0.0A,A,0se,0Km,0.0B,B,Dl,0S4,0.4P,P,0,0,0.0C,C,AJ,0L3,0.GT,T,0YM,16B,0.0D,D,1e3,0L3,0.4Q,Q,1Tm,0,0.GU,U,xQ,16B,0..YROA,Motor crank,Fe,Fe,0sg,0WU,c5cae9,O,A,,.YRAB,Drive link,Fe,Fe,0KS,0OQ,303e9f,A,B,,.YRBCPT,Wiper arm,Fe,Fe,02b,5H,0d125a,B,C,P,T,,.YRCD,Tie rod,Fe,Fe,vB,0L3,B2DFDB,C,D,,.YRDQU,Passenger arm,Fe,Fe,1Ll,GO,26A69A,D,Q,U,,...N_z',
  Elliptical_Crank:
    '2P.Ay,1E8.K,0.1011.6A,A,0ix,X,0.0B,B,0zu,7O,0.0C,C,0qC,Lr,0.GD,D,085,Av,0.0E,E,aY,v,0.4F,F,0,0,0.5P,P,aY,v,03..YRAB,AB,Fe,Fe,0rQ,3y,c5cae9,A,B,,.YRBC,BC,Fe,Fe,0v2,Ed,303e9f,B,C,,.YRCDE,CDE,Fe,Fe,07x,BD,0d125a,C,D,E,,.YRDF,DF,Fe,Fe,043,5S,B2DFDB,D,F,,.YPEP,EP,Fe,0,0,0,,E,P,,...N_V',
  Jansen_Leg:
    '2P.1jO,1E8.K,0.1011.6O,O,0,0,0.0A,A,3gO,0,0.4G,G,09Hm,01vu,0.0B,B,05tE,7ee,0.0C,C,0IGg,1-F,0.0D,D,06b8,0B7B,0.0E,E,0ETW,06sL,0.GF,F,0AYO,0MPj,0..YROA,OA,Fe,Fe,1rC,0,c5cae9,O,A,,.YRAB,AB,Fe,Fe,016R,3qK,303e9f,A,B,,.YRGBC,GBC,Fe,Fe,0B8Z,2ag,0d125a,G,B,C,,.YRAD,AD,Fe,Fe,01TO,05Zc,B2DFDB,A,D,,.YRGD,GD,Fe,Fe,07xS,06WY,26A69A,G,D,,.YRCE,CE,Fe,Fe,0GN5,02RZ,00695C,C,E,,.YRDEF,DEF,Fe,Fe,0AXh,0DT4,c5cae9,D,E,F,,...N_c',
  Backhoe_Bucket:
    '2P.Ay,1E8.K,0.1011.4A,A,01jO,0,0.0B,B,0sb,Py,0.8C,C,018N,HX,0.0D,D,0Ha,hT,0.4G,G,0,0,0.0H,H,VG,Im,0.4J,J,o0,0P0,0.0K,K,1BI,2i,0.0T,T,1NW,0ee,0.ZE,E,018N,HX,0,AB,A,B..YRAB,AB,Fe,Fe,01H-,C_,c5cae9,A,B,,.YRCD,CD,Fe,Fe,0iz,UV,303e9f,C,D,,.YRDGH,DGH,Fe,Fe,4a,Kl,0d125a,D,G,H,,.YRHK,HK,Fe,Fe,rH,Ak,B2DFDB,H,K,,.YRJKT,JKT,Fe,Fe,16x,0K-,26A69A,J,K,T,,.YPCE,CE,Fe,0,0,0,,C,E,,...N_0',
  Toggle_Press:
    '2P.Ay,1E8.K,0.1011.4A,A,01z0,0,0.0B,B,017k,0Uc,0.8C,C,01P8,0Kc,0.0D,D,0Zs,0pD,0.4G,G,0,0,0.0R,R,0,01cP,0.ZE,E,01P8,0Kc,0,AB,A,B.5F,F,0,01cP,OZ..YRAB,AB,Fe,Fe,01YN,0FJ,c5cae9,A,B,,.YRCD,CD,Fe,Fe,0_V,0Zv,303e9f,C,D,,.YRGD,GD,Fe,Fe,0Hx,0Pc,0d125a,G,D,,.YRDR,DR,Fe,Fe,0Hx,01Cp,B2DFDB,D,R,,.YPCE,CE,Fe,0,0,0,,C,E,,.YPRF,RF,Fe,0,0,0,,R,F,,...N_S',
  Scissor_Lift:
    '2P.Ay,1E8.K,0.1011.4A,A,2SG,0,0.0B,B,1fl,a3,0.8C,C,1wL,OD,0.0D,D,17q,yH,0.4G,G,0,0,0.0M,M,1Vm,1GM,0.0K,K,2-X,2Wj,0.0S,S,2-X,0,0.0T,T,0,2Wj,0.0U,U,3_1,2Wj,0.ZE,E,1wL,OD,0,AB,A,B.5N,N,2-X,0,0.1P,P,2-X,2Wj,0,TU,T,U..YRAB,AB,Fe,Fe,230,I2,c5cae9,A,B,,.YRCD,CD,Fe,Fe,1X5,gF,303e9f,C,D,,.YRGDMK,GDMK,Fe,Fe,1Pn,1BL,0d125a,G,D,M,K,,.YRSMT,SMT,Fe,Fe,1Vm,1GM,B2DFDB,S,M,T,,.YRTU,TU,Fe,Fe,1-0,2Wj,26A69A,T,U,,.YPCE,CE,Fe,0,0,0,,C,E,,.YPSN,SN,Fe,0,0,0,,S,N,,.YPKP,KP,Fe,0,0,0,,K,P,,...N_e',
  Shaper_Quick_Return:
    '2P.Ay,1E8.K,0.1011.6A,A,0,0,0.0B,B,Fe,0,0.4C,C,0,0ku,0.0D,D,Oj,RF,0.0R,R,qW,si,0.1P,P,Fe,0,0,CD,C,D.5Q,Q,qW,si,0..YRAB,AB,Fe,Fe,7q,0,c5cae9,A,B,,.YRCD,CD,Fe,Fe,CN,09q,303e9f,C,D,,.YRDR,DR,Fe,Fe,cd,e_,0d125a,D,R,,.YPBP,BP,Fe,0,0,0,,B,P,,.YPRQ,RQ,Fe,0,0,0,,R,Q,,...N_H',
  Pedaling_Leg:
    '2P.Ay,1E8.K,0.1011.4B,B,0,0,0.GP,P,Qa,0,0.4H,H,0NS,1Qe,0.2K,K,c5,13o,0..YRHK,HK,Fe,Fe,7L,1FD,c5cae9,H,K,,.YRKP,KP,Fe,Fe,WL,Xv,303e9f,K,P,,.YRBP,BP,Fe,Fe,DI,0,0d125a,B,P,,...N_p',
  Oscillating_Fan:
    '2P.Ay,1E8.K,0.1011.4A,A,0,0,0.2C,C,s8,0VG,0.0D,D,k_,0j9,0.4B,B,0GY,0In,0.0N,N,1NW,0,0..YRACN,ACN,Fe,Fe,lD,0AR,c5cae9,A,C,N,,.YRCD,CD,Fe,Fe,oZ,0cC,303e9f,C,D,,.YRDB,DB,Fe,Fe,FE,0Vz,0d125a,D,B,,...N_B',
  Pumpjack:
    '2P.Ay,1E8.K,0.1011.4A,A,0gB,0oI,0.0M,M,0QZ,0o1,0.2P,P,0d4,0,0.4S,S,0,0,0.0H,H,o0,0,0.0R,R,r8,0eW,0.5W,W,r8,0eW,OZ..YRAM,AM,Fe,Fe,0YN,0oA,c5cae9,A,M,,.YRMP,MP,Fe,Fe,0Wq,0P1,303e9f,M,P,,.YRPSH,PSH,Fe,Fe,3f,0,0d125a,P,S,H,,.YRHR,HR,Fe,Fe,pa,0KG,B2DFDB,H,R,,.YPRW,RW,Fe,0,0,0,,R,W,,...N_Z',
  Punch_Press:
    '2P.Ay,1E8.K,0.1011.6A,A,0,0,0.0B,B,0,Im,0.0C,C,0,0r8,0.5P,P,0,0r8,OZ..YRAB,Crank,VG,o,0,9O,c5cae9,A,B,,.YRBC,Connecting rod,ku,6G,0,0HC,303e9f,B,C,,.YPCP,CP,1Tm,0,0,0,,C,P,,..2F1,BC,F1,0,0r8,0,0bW,1Xg0..N_J',
  Derrick_Crane:
    '2P.Ay,1E8.K,0.1011.4O,O,0,0,0.0C,C,Qv,cP,0.0T,T,rn,1Cp,0.6G,G,YO,09O,0.0K,K,Mp,18,0..YRGK,Luffing crank,VG,o,Sc,048,c5cae9,G,K,,.YRCK,Luffing link,ku,6G,Os,Jn,303e9f,C,K,,.YROCT,Boom,2xW,ku,Qv,cP,0d125a,O,C,T,,..2F1,OCT,F1,rn,1Cp,rn,zB,z2G..N_v',
  Toggle_Clamp:
    '2P.Ay,1E8.K,0.1011.6H,H,0ee,Ti,0.0E,E,09O,NS,0.0P,P,P0,5U,0.4N,N,0Lu,09O,0..YRHE,Handle,NS,o,0P0,Qa,c5cae9,H,E,,.YREP,Toggle link,Fe,1G,7q,ET,303e9f,E,P,,.YRNP,Clamp bar,VG,38,1a,01z,0d125a,N,P,,..2F1,NP,F1,P0,5U,P0,L6,hyW..N_e',
  Offset_Load_Rocker:
    '2P.Ay,1E8.K,0.1011.6A,A,0,0,0.0B,B,HC,7q,0.0C,C,104,bW,0.4D,D,1E8,0,0.0L,L,1SC,jK,0..YRAB,Crank,VG,o,8c,3w,c5cae9,A,B,,.YRBC,Coupler,_W,7q,ee,Mg,303e9f,B,C,,.YRCDL,Rocker,1E8,E4,1E8,Rd,0d125a,C,D,L,,..2F1,CDL,F1,1SC,jK,1Fi,Zy,adm..N_l',
  // </generated>
};
