// joint.ts first: the model modules form an import cycle that only
// initializes cleanly when entered here (see test-utils/verification/fixture.ts).
import '../../app/model/joint';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  LIBRARY_TEMPLATE_IDS,
  TEMPLATE_IDS,
  TEMPLATE_LINKAGES,
} from '../../app/component/MODALS/templates/template-linkages';
import { fixturePayload } from '../../test-utils/verification/fixture-gallery';
import { libraryTemplateEntry } from '../../test-utils/verification/template-fixtures';
import { StringTranscoder } from '../../app/services/transcoding/string-transcoder';
import { buildMechanismFixture } from '../fixtures/mechanism-fixtures';

// The library templates are generated, not typed in. A template and the fixture
// a spec asserts on are the same mechanism, and this is what keeps them that
// way: encode the fixture, compare against what is checked in, and fail with
// the command that fixes it. Same contract as docs/fixture-urls.md.
//
// Run `npm run template-payloads` to regenerate.

const SOURCE_PATH = resolve(__dirname, '../../app/component/MODALS/templates/template-linkages.ts');
const START = '  // <generated by `npm run template-payloads` — do not edit by hand>';
const END = '  // </generated>';

/** The generated block, formatted the way Prettier leaves it in the source. */
function generatedBlock(): string {
  const entries = LIBRARY_TEMPLATE_IDS.map((id) => {
    const entry = libraryTemplateEntry(id);
    // The same payload the published gallery links to, drawing scale included:
    // the card and the doc row are the same picture of the same mechanism.
    return `  ${id}:\n    '${fixturePayload(entry.fixture, entry.objectScale, entry.speed)}',`;
  });
  return [START, ...entries, END].join('\n');
}

function replaceBlock(source: string, block: string): string {
  const from = source.indexOf(START);
  const to = source.indexOf(END);
  if (from < 0 || to < 0) throw new Error('template-linkages.ts has lost its generated markers');
  return source.slice(0, from) + block + source.slice(to + END.length);
}

describe('library template payloads', () => {
  it('match what their verification fixtures encode to', () => {
    const source = readFileSync(SOURCE_PATH, 'utf8');
    const regenerated = replaceBlock(source, generatedBlock());
    if (process.env['PMKS_WRITE_TEMPLATE_PAYLOADS']) {
      writeFileSync(SOURCE_PATH, regenerated);
      return;
    }
    expect(source, 'run `npm run template-payloads`').toBe(regenerated);
  });
});

describe('every template the library dialog offers', () => {
  for (const id of TEMPLATE_IDS) {
    describe(id, () => {
      it('decodes without throwing', () => {
        const decoder = new StringTranscoder();
        expect(() => decoder.decodeURL(TEMPLATE_LINKAGES[id])).not.toThrow();
        expect(decoder.getJoints().length).toBeGreaterThan(1);
      });

      it('reports one degree of freedom and precomputes a cycle', () => {
        // A template that opens to a linkage the user cannot play is worse than
        // no template: the dialog promises a working example.
        const { mechanism } = buildMechanismFixture(TEMPLATE_LINKAGES[id]);
        expect(mechanism.isMechanismValid()).toBe(true);
        expect(mechanism.dof).toBe(1);
        expect(mechanism.joints.length).toBeGreaterThan(20);
      });
    });
  }
});
